### ISSUE TITLE
Error after installing VS 2022 and updating OS to Win 10 20H2

### ISSUE THREAD

**Issue by br549times3** [mmajcica/DevEnvBuild#22]
I have build tasks that use devenv and they were working, but after installing VS 2022 and also updating Windows 10 from 1803 to 20H2 version and also WSL 2.0 if it has any impact.  

I am getting error:

Description  : Build a project via the visual studio command-line invocation, devenv.cmd. Used for building eg. SSIS projects.
Version      : 2.0.5
Author       : Mario Majcica
Help         : Build your project via the visual studio command-line invocation, devenv.cmd

##[error]Cannot process argument transformation on parameter 'FileName'. Cannot convert value to type System.String.

![image](https://user-images.githubusercontent.com/28811413/149544046-ed0a0171-0c7f-456a-80d7-31c48ed46165.png)

**Comment by br549times3** [comment]
My task setting is set to VS 2019 and using a path:   Common/File.sln

**Comment by henrypedersen77** [comment]
We have the same issue, after installing VS 2022 on the build server, then all our piplines that uses this component is failing, withe the same error message. Are you looking into fixing this issue? Please :-)

**Comment by Gitprojekter** [comment]
All our devops pipelines that uses this component is failing and we have around 80 pipelines which build using VS2019 and not VS2022.
Why VS2022 impact this  component  I don't have any idea.

We have a release in 2 weeks where we should be able to build from the build server. It will be a big job to replace all our builds with something else, because we are otherwise happy with this component.

Do you have any idea when you can have a fix that solve issue.

**Comment by cbolsen** [comment]
I'm seeing the same issue after installing VS2022 on the build server, even if I set the version option to "Visual Studio 2019".

**Comment by cbolsen** [comment]
The problem was resolved by removing VS2019. It seems the task has trouble resolving the path when more than one version is installed, similar to #11
